# application-discovery.yml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:nacos1:8848,nacos2:8848}
        namespace: ${NACOS_NAMESPACE}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        cluster-name: ${CLUSTER_NAME:DEFAULT}
        metadata:
          version: ${APPLICATION_VERSION:1.0.0}
          env: ${SPRING_PROFILES_ACTIVE:prod}
        # 健康检查
        health-check:
          enabled: true
          interval: 5000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        file-extension: yaml
        # 支持共享配置
        shared-configs:
          - data-id: common-config.yaml
            group: ${NACOS_GROUP:DEFAULT_GROUP}
            refresh: true
          - data-id: security-config.yaml
            group: ${NACOS_GROUP:DEFAULT_GROUP}
            refresh: true

    # 服务调用配置
    loadbalancer:
      enabled: true
      retry:
        enabled: true
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s