# application-security.yml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.company.com
          jwk-set-uri: https://auth.company.com/.well-known/jwks.json

    # CORS配置
    cors:
      allowed-origins:
        - https://*.company.com
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - Authorization
        - Content-Type
      exposed-headers:
        - X-Total-Count
      allow-credentials: true
      max-age: 1800

server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: platform-collect
  http2:
    enabled: true

collect:
  security:
    # JWT配置
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000

    # 密码策略
    password:
      min-length: 8
      require-upper: true
      require-lower: true
      require-digit: true
      require-special: true
      history-count: 5

    # IP限制
    ip-filter:
      enabled: true
      whitelist:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      blacklist: []

    # API访问限制
    rate-limit:
      enabled: true
      default-limit: 100
      period: 60

    # 敏感数据加密
    encryption:
      enabled: true
      algorithm: AES
      key: ${ENCRYPTION_KEY}

    # 审计日志
    audit:
      enabled: true
      log-type: db # db, file, both